### PR TITLE
Allow newer versions of the listen gem

### PR DESCRIPTION
**Pull request by faramund**
I allowed new versions of listen. All tests are successful and my app, which uses mailman, works correctly.

### CODE REVIEW

**Comment by Mic92** [comment]
Wouldn't it be sensible to add a < 4.0, because of future breakage.

**Comment by faramund** [comment]
You are right. I noticed that a mail gem in gemspec has ">=", so I did it. Why in that case is sensible ?

**Comment by Mic92** [comment]
Probably not, @titanous has introduced this.

**Comment by faramund** [comment]
Ok. What do you think about change the listen gem  ~>3.0 or >= 2.2 <= 3.0 ? It is sensible.

**Comment by Mic92** [comment]
As I don't expect API breakages in any 3.x version of listen, I would say:

```
spec.add_runtime_dependency 'listen', '>= 2.2', '< 4'
```

**Comment by faramund** [comment]
I agree with you. Will you commit and merge this line ?

**Comment by Mic92** [comment]
yes

**Pull request closed without merging**
